spring.application.name=blogging

spring.datasource.url=jdbc:postgresql://localhost:5432/blogposts
spring.datasource.username=postgres
spring.datasource.password='chinazaC3@'
spring.jpa.hibernate.ddl-auto=update