spring.application.name=blogging

spring.datasource.url=jdbc:postgresql://localhost:5432/blogposts
spring.datasource.username=postgres
spring.datasource.password=''
spring.jpa.hibernate.ddl-auto=update

# http://localhost:8080/books